"""Catalogo degli ingredienti comuni italiani: categoria e prezzo medio.

È la fonte unica per due cose: il seed dell'anagrafica (`python -m app.seed`) e la
classificazione degli ingredienti nuovi che l'AI inventa strada facendo. I prezzi
sono medie da supermercato: servono a dare un ordine di grandezza al totale della
spesa, non a fare il conto esatto alla cassa.

Formato: nome → (categoria, prezzo medio, unità di prezzo).
"""

INGREDIENT_CATALOG: dict[str, tuple[str, float, str]] = {
    # ── Verdura ──
    "zucchine": ("verdura", 2.50, "kg"),
    "melanzane": ("verdura", 2.60, "kg"),
    "pomodori": ("verdura", 2.80, "kg"),
    "pomodorini": ("verdura", 4.00, "kg"),
    "pomodori pelati": ("verdura", 1.80, "kg"),
    "passata di pomodoro": ("verdura", 1.60, "kg"),
    "peperoni": ("verdura", 3.00, "kg"),
    "carote": ("verdura", 1.50, "kg"),
    "cipolle": ("verdura", 1.60, "kg"),
    "cipolla rossa": ("verdura", 2.20, "kg"),
    "aglio": ("verdura", 6.00, "kg"),
    "sedano": ("verdura", 2.00, "kg"),
    "patate": ("verdura", 1.40, "kg"),
    "patate dolci": ("verdura", 3.00, "kg"),
    "spinaci": ("verdura", 3.50, "kg"),
    "bietola": ("verdura", 2.50, "kg"),
    "broccoli": ("verdura", 2.80, "kg"),
    "cavolfiore": ("verdura", 2.40, "kg"),
    "cavolo nero": ("verdura", 3.00, "kg"),
    "verza": ("verdura", 1.80, "kg"),
    "finocchi": ("verdura", 2.40, "kg"),
    "radicchio": ("verdura", 3.20, "kg"),
    "lattuga": ("verdura", 2.50, "kg"),
    "rucola": ("verdura", 8.00, "kg"),
    "insalata mista": ("verdura", 6.00, "kg"),
    "cetrioli": ("verdura", 2.20, "kg"),
    "zucca": ("verdura", 2.00, "kg"),
    "asparagi": ("verdura", 7.00, "kg"),
    "carciofi": ("verdura", 4.00, "kg"),
    "funghi champignon": ("verdura", 5.00, "kg"),
    "funghi porcini": ("verdura", 18.00, "kg"),
    "fagiolini": ("verdura", 4.00, "kg"),
    "piselli": ("verdura", 3.50, "kg"),
    "porri": ("verdura", 2.80, "kg"),
    "cicoria": ("verdura", 3.00, "kg"),
    "cavolini di bruxelles": ("verdura", 4.50, "kg"),
    "prezzemolo": ("verdura", 12.00, "kg"),
    "basilico": ("verdura", 15.00, "kg"),
    "rosmarino": ("verdura", 15.00, "kg"),
    "salvia": ("verdura", 15.00, "kg"),
    # ── Frutta ──
    "mele": ("frutta", 2.20, "kg"),
    "pere": ("frutta", 2.50, "kg"),
    "banane": ("frutta", 1.90, "kg"),
    "arance": ("frutta", 2.00, "kg"),
    "mandarini": ("frutta", 2.40, "kg"),
    "limoni": ("frutta", 2.60, "kg"),
    "pompelmo": ("frutta", 2.40, "kg"),
    "kiwi": ("frutta", 3.00, "kg"),
    "fragole": ("frutta", 6.00, "kg"),
    "ciliegie": ("frutta", 8.00, "kg"),
    "pesche": ("frutta", 2.80, "kg"),
    "albicocche": ("frutta", 3.50, "kg"),
    "susine": ("frutta", 3.00, "kg"),
    "uva": ("frutta", 3.20, "kg"),
    "melone": ("frutta", 2.00, "kg"),
    "anguria": ("frutta", 1.20, "kg"),
    "fichi": ("frutta", 6.00, "kg"),
    "cachi": ("frutta", 3.00, "kg"),
    "melagrana": ("frutta", 4.00, "kg"),
    "mirtilli": ("frutta", 18.00, "kg"),
    "lamponi": ("frutta", 22.00, "kg"),
    "ananas": ("frutta", 2.50, "kg"),
    "avocado": ("frutta", 8.00, "kg"),
    "frutta secca mista": ("frutta", 16.00, "kg"),
    "mandorle": ("frutta", 16.00, "kg"),
    "noci": ("frutta", 14.00, "kg"),
    "nocciole": ("frutta", 18.00, "kg"),
    "pinoli": ("frutta", 60.00, "kg"),
    "pistacchi": ("frutta", 22.00, "kg"),
    "uvetta": ("frutta", 7.00, "kg"),
    # ── Carne ──
    "petto di pollo": ("carne", 9.50, "kg"),
    "cosce di pollo": ("carne", 6.00, "kg"),
    "fesa di tacchino": ("carne", 11.00, "kg"),
    "manzo macinato": ("carne", 12.00, "kg"),
    "fettine di manzo": ("carne", 14.00, "kg"),
    "vitello": ("carne", 18.00, "kg"),
    "lonza di maiale": ("carne", 8.50, "kg"),
    "salsiccia": ("carne", 9.00, "kg"),
    "prosciutto crudo": ("carne", 28.00, "kg"),
    "prosciutto cotto": ("carne", 14.00, "kg"),
    "bresaola": ("carne", 32.00, "kg"),
    "speck": ("carne", 24.00, "kg"),
    "pancetta": ("carne", 14.00, "kg"),
    "guanciale": ("carne", 18.00, "kg"),
    "coniglio": ("carne", 12.00, "kg"),
    # ── Pesce ──
    "salmone": ("pesce", 24.00, "kg"),
    "salmone affumicato": ("pesce", 34.00, "kg"),
    "merluzzo": ("pesce", 14.00, "kg"),
    "orata": ("pesce", 13.00, "kg"),
    "branzino": ("pesce", 14.00, "kg"),
    "tonno fresco": ("pesce", 22.00, "kg"),
    "tonno in scatola": ("pesce", 14.00, "kg"),
    "sgombro": ("pesce", 8.00, "kg"),
    "alici": ("pesce", 9.00, "kg"),
    "gamberi": ("pesce", 18.00, "kg"),
    "calamari": ("pesce", 14.00, "kg"),
    "seppie": ("pesce", 12.00, "kg"),
    "cozze": ("pesce", 5.00, "kg"),
    "vongole": ("pesce", 12.00, "kg"),
    "platessa": ("pesce", 12.00, "kg"),
    # ── Latticini e uova ──
    "latte": ("latticini", 1.40, "l"),
    "latte scremato": ("latticini", 1.40, "l"),
    "yogurt greco": ("latticini", 6.00, "kg"),
    "yogurt bianco": ("latticini", 3.50, "kg"),
    "ricotta": ("latticini", 8.00, "kg"),
    "mozzarella": ("latticini", 9.00, "kg"),
    "mozzarella di bufala": ("latticini", 16.00, "kg"),
    "parmigiano reggiano": ("latticini", 22.00, "kg"),
    "grana padano": ("latticini", 16.00, "kg"),
    "pecorino": ("latticini", 20.00, "kg"),
    "stracchino": ("latticini", 12.00, "kg"),
    "philadelphia": ("latticini", 12.00, "kg"),
    "fiocchi di latte": ("latticini", 8.00, "kg"),
    "burro": ("latticini", 12.00, "kg"),
    "panna da cucina": ("latticini", 4.00, "l"),
    "uova": ("uova", 0.35, "unità"),
    "albume": ("uova", 6.00, "l"),
    # ── Cereali e derivati ──
    "pasta": ("cereali", 1.80, "kg"),
    "pasta integrale": ("cereali", 2.40, "kg"),
    "riso": ("cereali", 2.50, "kg"),
    "riso integrale": ("cereali", 3.20, "kg"),
    "riso basmati": ("cereali", 3.50, "kg"),
    "orzo perlato": ("cereali", 2.60, "kg"),
    "farro": ("cereali", 3.20, "kg"),
    "quinoa": ("cereali", 7.00, "kg"),
    "cous cous": ("cereali", 3.00, "kg"),
    "pane": ("cereali", 3.50, "kg"),
    "pane integrale": ("cereali", 4.00, "kg"),
    "fette biscottate": ("cereali", 4.50, "kg"),
    "pane azzimo": ("cereali", 6.00, "kg"),
    "farina 00": ("cereali", 1.20, "kg"),
    "farina integrale": ("cereali", 1.80, "kg"),
    "polenta": ("cereali", 2.00, "kg"),
    "avena": ("cereali", 3.00, "kg"),
    "fiocchi d'avena": ("cereali", 3.00, "kg"),
    "pangrattato": ("cereali", 2.50, "kg"),
    "gnocchi": ("cereali", 3.00, "kg"),
    "couscous integrale": ("cereali", 3.60, "kg"),
    # ── Legumi ──
    "ceci": ("legumi", 3.00, "kg"),
    "ceci in scatola": ("legumi", 2.20, "kg"),
    "lenticchie": ("legumi", 3.20, "kg"),
    "fagioli borlotti": ("legumi", 3.00, "kg"),
    "fagioli cannellini": ("legumi", 3.00, "kg"),
    "fave secche": ("legumi", 3.50, "kg"),
    "piselli secchi": ("legumi", 2.80, "kg"),
    "soia": ("legumi", 4.00, "kg"),
    "tofu": ("legumi", 9.00, "kg"),
    "hummus": ("legumi", 10.00, "kg"),
    # ── Condimenti e dispensa ──
    "olio extravergine di oliva": ("condimenti", 9.00, "l"),
    "olio di semi": ("condimenti", 2.50, "l"),
    "aceto di vino": ("condimenti", 2.00, "l"),
    "aceto balsamico": ("condimenti", 6.00, "l"),
    "sale": ("condimenti", 0.60, "kg"),
    "pepe nero": ("condimenti", 30.00, "kg"),
    "zucchero": ("condimenti", 1.20, "kg"),
    "miele": ("condimenti", 12.00, "kg"),
    "origano": ("condimenti", 40.00, "kg"),
    "peperoncino": ("condimenti", 35.00, "kg"),
    "curry": ("condimenti", 35.00, "kg"),
    "paprika": ("condimenti", 30.00, "kg"),
    "curcuma": ("condimenti", 30.00, "kg"),
    "cannella": ("condimenti", 40.00, "kg"),
    "noce moscata": ("condimenti", 60.00, "kg"),
    "senape": ("condimenti", 8.00, "kg"),
    "salsa di soia": ("condimenti", 6.00, "l"),
    "brodo vegetale": ("condimenti", 2.00, "l"),
    "lievito": ("condimenti", 20.00, "kg"),
    "cacao amaro": ("condimenti", 14.00, "kg"),
    "cioccolato fondente": ("condimenti", 16.00, "kg"),
    "vino bianco": ("bevande", 5.00, "l"),
    "vino rosso": ("bevande", 5.00, "l"),
    # ── Surgelati ──
    "spinaci surgelati": ("surgelati", 3.00, "kg"),
    "minestrone surgelato": ("surgelati", 2.80, "kg"),
    "piselli surgelati": ("surgelati", 2.50, "kg"),
    "filetti di merluzzo surgelati": ("surgelati", 12.00, "kg"),
}

# Ingredienti proposti come "di base" al primo avvio: quelli che chiunque ha in casa
# e che in lista della spesa farebbero solo rumore.
DEFAULT_BASE_INGREDIENTS = [
    "olio extravergine di oliva",
    "sale",
    "pepe nero",
    "aceto di vino",
    "zucchero",
    "aglio",
    "origano",
]

# Parole chiave per indovinare la categoria di un ingrediente che non è a catalogo
# (l'AI ne inventa di continuo). L'ordine conta: la prima che matcha vince.
_CATEGORY_KEYWORDS: list[tuple[str, tuple[str, ...]]] = [
    ("pesce", ("pesce", "salmone", "tonno", "merluzzo", "orata", "branzino", "gambero",
               "calamar", "seppi", "cozz", "vongol", "alici", "acciug", "sgombro",
               "platessa", "polpo", "sogliola", "trota", "baccalà")),
    ("carne", ("pollo", "tacchino", "manzo", "vitello", "maiale", "agnello", "coniglio",
               "salsicc", "prosciutto", "bresaola", "speck", "pancetta", "guanciale",
               "wurstel", "hamburger", "carne", "bistecc", "arrosto", "mortadella",
               "salame")),
    ("latticini", ("latte", "yogurt", "ricotta", "mozzarella", "formaggio", "parmigiano",
                   "grana", "pecorino", "stracchino", "mascarpone", "burro", "panna",
                   "scamorza", "provola", "gorgonzola", "feta", "philadelphia",
                   "fiocchi di latte", "caciotta")),
    ("uova", ("uovo", "uova", "albume", "tuorlo")),
    ("legumi", ("cec", "lentic", "fagiol", "fave", "piselli secchi", "soia", "tofu",
                "tempeh", "hummus", "lupini", "edamame")),
    ("cereali", ("pasta", "riso", "pane", "farina", "farro", "orzo", "quinoa", "avena",
                 "cous", "polenta", "gnocchi", "crackers", "fette biscottate", "cereali",
                 "grissini", "piadina", "tortilla", "bulgur", "miglio", "mais",
                 "pangrattato", "biscott")),
    ("frutta", ("mel", "pera", "banana", "arance", "arancia", "mandarin", "limon",
                "pompelmo", "kiwi", "fragol", "cilieg", "pesc", "albicocc", "susin",
                "uva", "melone", "anguria", "fich", "cachi", "melagrana", "mirtill",
                "lampon", "ananas", "avocado", "mandorl", "noci", "nocciol", "pinoli",
                "pistacch", "uvetta", "datter", "prugn", "frutta")),
    ("surgelati", ("surgelat", "congelat")),
    ("bevande", ("acqua", "vino", "birra", "succo", "tè", "the", "caffè", "bevanda")),
    ("condimenti", ("olio", "aceto", "sale", "pepe", "zucchero", "miele", "spezi",
                    "origano", "peperoncino", "curry", "paprika", "curcuma", "cannella",
                    "noce moscata", "senape", "salsa", "brodo", "lievito", "cacao",
                    "cioccolat", "vaniglia", "maionese", "ketchup", "erbe", "aroma")),
    ("verdura", ("zucchin", "melanzan", "pomodor", "peperon", "carot", "cipoll", "aglio",
                 "sedano", "patat", "spinac", "bietol", "broccol", "cavol", "verza",
                 "finocch", "radicch", "lattug", "rucola", "insalat", "cetriol", "zucca",
                 "asparag", "carciof", "fungh", "fagiolin", "pisell", "porr", "cicoria",
                 "prezzemolo", "basilico", "rosmarino", "salvia", "menta", "ravanell",
                 "barbabietol", "sedano rapa", "topinambur", "germogli", "verdur")),
]


def guess_category(name: str) -> str:
    """Categoria per un ingrediente non a catalogo. Ripiega su "altro"."""
    n = name.strip().lower()
    for category, keywords in _CATEGORY_KEYWORDS:
        if any(k in n for k in keywords):
            return category
    return "altro"


def catalog_entry(name: str) -> tuple[str, float, str] | None:
    return INGREDIENT_CATALOG.get(name.strip().lower())
